export const icon = (kind, key) => `<img src="${icons[kind]?.[key] || icons.fallback}" width="24" height="24" alt="${key}" title="${key}" />`;

export const icons = {
  languages: {
    Java: "https://upload.wikimedia.org/wikipedia/ru/3/39/Java_logo.svg",
    "C#": "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg",
    JavaScript: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
    Markdown: "https://upload.wikimedia.org/wikipedia/commons/4/48/Markdown-mark.svg",
    YAML: "https://upload.wikimedia.org/wikipedia/commons/6/63/YAML_logo_in_SVG_format.svg",
    TypeScript: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg",
    HTML: "https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg",
    JSON: "https://upload.wikimedia.org/wikipedia/commons/c/c9/JSON_vector_logo.svg",
    Bash: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Bash_Logo_Colored.svg",
    Python: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg",
    SQL: "https://symbols.getvecta.com/stencil_28/61_sql-database-generic.a9f12e2a30.svg",
    Groovy: "https://upload.wikimedia.org/wikipedia/commons/3/36/Groovy-logo.svg",
    PHP: "https://upload.wikimedia.org/wikipedia/commons/2/27/PHP-logo.svg",
    XML: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Xml_logo.svg",
    CSS: "https://cdn1.iconfinder.com/data/icons/logotypes/32/badge-css-3-256.png",
    GraphQL: "https://upload.wikimedia.org/wikipedia/commons/1/17/GraphQL_Logo.svg",
    Go: "https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg",
    Git: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Git_icon.svg",
    JSX: "https://ru.wikipedia.org/wiki/React#/media/%D0%A4%D0%B0%D0%B9%D0%BB:React-icon.svg",
    Kotlin: "https://upload.wikimedia.org/wikipedia/commons/0/06/Kotlin_Icon.svg",
    Haskell: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Haskell-Logo.svg",
    Swift: "https://cdn.worldvectorlogo.com/logos/swift-15.svg",
    Terraform: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/terraform/terraform-original.svg",
    Dockerfile: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg",
    Shell: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bash/bash-original.svg",
    PowerShell: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bash/bash-original.svg",
  },
  fallback: "https://www.svgrepo.com/show/149905/txt-file-symbol.svg",
  editors: {
    "VS Code": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Visual_Studio_Code_1.35_icon.svg",
    Chrome: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Google_Chrome_icon_%28September_2014%29.svg",
    "Android Studio": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Breezeicons-apps-48-android-studio.svg",
    Browser: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Google_Chrome_icon_%28September_2014%29.svg",
    // https://www.jetbrains.com/ru-ru/company/brand/
    WebStorm: "https://resources.jetbrains.com/storage/products/company/brand/logos/WebStorm_icon.svg",
    IntelliJ: "https://resources.jetbrains.com/storage/products/company/brand/logos/IntelliJ_IDEA_icon.svg",
    Rider: "https://resources.jetbrains.com/storage/products/company/brand/logos/Rider_icon.svg",
    PyCharm: "https://resources.jetbrains.com/storage/products/company/brand/logos/PyCharm_icon.svg",
  },
  platforms: {
    Mac: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
    Windows: "https://upload.wikimedia.org/wikipedia/commons/3/34/Windows_logo_-_2012_derivative.svg",
    Linux: "https://upload.wikimedia.org/wikipedia/commons/3/35/Tux.svg",
  },
  stats: {
    requests: "assets/icons/pullrequest.svg",
    commits: "assets/icons/commit.svg",
    issues: "assets/icons/issue.svg",
    stars: "assets/icons/star.svg",
    contributions: "assets/icons/merge.svg",
  },
};
